### ISSUE TITLE
1 + 2.0でエラーになる

### ISSUE THREAD

**Issue by kacchi** [ymdpn/add#7]
```
$ java -cp target/add-1.0.jar:$HOME/.m2/repository/commons-lang/comm
ons-lang/2.6/commons-lang-2.6.jar com.example.Add 1 2.0
Exception in thread "main" java.lang.NumberFormatException: For input string: "2.0"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at com.example.Add.main(Add.java:15)
```

**Comment by ymdpn** [comment]
整数値のみ許容することとし、それ以外のデータ型が入力された場合はリターンコードを1として終了するようにしました。
